---
title: "новий док"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

### Змінні



```{r}
price_in_hryvnya <- c(200, 300, 400, 5000, 1)
currency_ratio <- 28
price_in_usd <- price_in_hryvnya / currency_ratio
```

### вектор

```{r}
v <- c(1.2, 34.5, 13.1)
v + 1:30
v <- c(1:100)
v[51] # 51 element of vector
v[11:20]

v[c(1,5,25)]

text_vector <- c("one", "two", "three") 
text_vector[1]
text_vector[3]

paste(text_vector "number")
```

###Lists are created by list() function

```{r}
l1<- list(a = 1, b = 2, c = 3)
l1[1]


l1$a

```

```{r}
```
### Data Frame

```{r}
library(readr)
```

```{r}
name<- c("Ira","Vlad","Kate")
age<- c(22,21,21)
gender<- c("F", "M","F")

df<- data.frame(name,age,gender)

#write.csv(df,"namegrup.csv", sep = ";")
write_excel_csv(df,"namegrup.csv", delim=";")
```
###Loops

```{r}
for(i in c("one","two","three")){
  print(i)
}
```

###  if-else

```{r}
b <- 50

if(b > 2){
  print("The number is too big")
} else {
print("The number is too small")
}
```

